#
# Holds roles to be installed prior to executing playbooks:
#
#   ansible-galaxy install -r requirements.yml
#

# Install roles from ansible galaxy
#
- src: geerlingguy.postgresql
- src: Graylog2.graylog-ansible-role
- src: neel.rundeck
- src: dj-wasabi.zabbix-server
- src: dj-wasabi.zabbix-web
- src: inkatze.wildfly