#
# Create EC2 Instance with GP2 SSD Drive
#
- name: "Create ec2 instance ({{ name }})"
  tags:
    - vmdev
  ec2:
    aws_access_key:     "{{ aws_access_key }}"
    aws_secret_key:     "{{ aws_secret_key }}"    
    region:             "{{ aws_region }}"    
    key_name:           "{{ aws_keypair_name }}"
    image:              "{{ aws_centos_ami }}"
    group_id:           "{{ aws_vm_securitygroup_id }}"
    instance_type:      "{{ aws_default_size }}"
    vpc_subnet_id:      "{{ public_subnet_1_id }}"
    assign_public_ip:   yes
    wait:               yes
    wait_timeout:       500
    instance_tags:
      Name: "{{ name }}"
      purpose: vmdev
      service: "{{ service }}"
    volumes:
      - device_name:    /dev/xvda
        volume_type:    gp2
        volume_size:    30
    count_tag:
      Name:             "{{ name }}"
    exact_count:        1
  register:             ec2instance

- name: "Add new instance to host group ({{ ec2instance.instance_ids }})"
  tags:
    - vmdev
  add_host:
    hostname:           "{{ item.public_ip }}"
    groupname:          launched
  with_items:           "{{ ec2instance.instances }}"

- name: "Wait for the instance(s) to boot by checking the ssh port ({{ ec2instance.instance_ids }})"
  tags:
    - vmdev
  wait_for:             host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
  with_items:           "{{ ec2instance.instances }}"



