- name: "Terminate instance(s) that were previously launched ({{ instance_ids }})"
  tags:
    - terminate
  ec2:
    region: "{{ aws_region }}"    
    state: 'absent'
    instance_ids: '{{ instance_ids }}'